server:
  port: 8090 #포트 번호
spring:
  profiles:
    include: secret
  mail:
    host: smtp.gmail.com
    port: 587
    username: gsw643500@gmail.com
    password: NEED_TO_INPUT_ON_SECRET
    properties:
      mail:
        smtp:
          auth: ture
          starttls:
            enable: true
  output:
    ansi:
      enabled: always
  datasource: # 데이터베이스 연결
    driver-class-name: org.mariadb.jdbc.Driver # 사용할 데이터베이스 이름
    url: jdbc:mariadb://localhost:3306/mid_pro_dev # 데이터베이스 URL 지정
    username: root  # 데이터베이스 연결 사용자 이름
    password: # 데이터베이스 사용자 비밀번호
  security:
    user:
      name: user
      password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
custom:
  genFile:
    dirPath: c:/temp/demo5