server:
  port: 8090
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mid_pro_dev
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


